version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bookdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookapp
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bookdb
    ports:
      - "7777:7777"
    depends_on:
      - postgres

volumes:
  postgres_data:
